### ISSUE TITLE
fatal error: unexpected signal during runtime execution - golibwireshark.go:37

### ISSUE THREAD

**Issue by kairotavares** [sunwxg/golibwireshark#1]
Hi, 

Im trying to use the golibwireshark, but in every example I got an unexpected signal crashing the application when it try to use the init() function.
I already tried in some containers debian, ubuntu 15... but it didn`t woked.

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7effc091281a
runtime.throw(0x753325)
    /usr/lib/go/src/pkg/runtime/panic.c:520 +0x69
runtime: unexpected return pc for runtime.sigpanic called from 0x7effc091281a
runtime.sigpanic()
    /usr/lib/go/src/pkg/runtime/os_linux.c:222 +0x3d

goroutine 16 [syscall]:
runtime.cgocall(0x4028c8, 0x7effc0e2de58)
    /usr/lib/go/src/pkg/runtime/cgocall.c:143 +0xe5 fp=0x7effc0e2de40 sp=0x7effc0e2ddf8
github.com/sunwxg/golibwireshark._Cfunc_init(0x22609e0, 0x0, 0x22609e0)
    github.com/sunwxg/golibwireshark/_obj/_cgo_defun.c:146 +0x31 fp=0x7effc0e2de58 sp=0x7effc0e2de40
github.com/sunwxg/golibwireshark.Init(0x4d9050, 0xc, 0x4d2690, 0x0, 0x0, 0x0)
    /root/go/src/github.com/sunwxg/golibwireshark/golibwireshark.go:37 +0x69 fp=0x7effc0e2dea0 sp=0x7effc0e2de58
main.main()
    /root/tests/golibwireshark/example/printpacket/printPacket.go:12 +0x5c fp=0x7effc0e2df50 sp=0x7effc0e2dea0
runtime.main()
    /usr/lib/go/src/pkg/runtime/proc.c:247 +0x11a fp=0x7effc0e2dfa8 sp=0x7effc0e2df50
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445 fp=0x7effc0e2dfb0 sp=0x7effc0e2dfa8
created by _rt0_go
    /usr/lib/go/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 19 [finalizer wait]:
runtime.park(0x4165c0, 0x758af8, 0x755f09)
    /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x758af8, 0x755f09)
    /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445
exit status 2

```

Thanks

**Comment by sunwxg** [comment]
``` sh
cd  ${GOPATH}/src/github.com/sunwxg
cp include/cfile.h $(pkg-config --variable=includedir wireshark)/epan/

go build
go test
```

Please try up commands, what is `go test` result?
If `go test` result is ok, you can try example again.

Thanks.

**Comment by kairotavares** [comment]
Unfortunately, I got the same thing when I did `go test`.

The build seams ok.

In my linux machine:

```
:~/go/src/github.com/sunwxg/golibwireshark# go test
# github.com/sunwxg/golibwireshark_test
./golibwireshark_test.go:12: undefined: testing.M
FAIL    github.com/sunwxg/golibwireshark [build failed]
```

In the containers I got:

```
root@b92b84625c98:/go/src/github.com/sunwxg/golibwireshark# go test
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x5c61c0, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x50d4e6, 0xc820049d78, 0x0)
    /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820049d40 sp=0xc820049d10
github.com/sunwxg/golibwireshark._Cfunc_init(0x284e9e0, 0x284eab0, 0x0)
    ??:0 +0x41 fp=0xc820049d78 sp=0xc820049d40
github.com/sunwxg/golibwireshark.Init(0x58d010, 0x6, 0x58efe0, 0x6, 0x0, 0x0)
    /go/src/github.com/sunwxg/golibwireshark/golibwireshark.go:39 +0x106 fp=0xc820049dc0 sp=0xc820049d78
github.com/sunwxg/golibwireshark_test.TestMain(0xc820049ef8)
    /go/src/github.com/sunwxg/golibwireshark/golibwireshark_test.go:14 +0x62 fp=0xc820049e60 sp=0xc820049dc0
main.main()
    github.com/sunwxg/golibwireshark/_test/_testmain.go:56 +0x114 fp=0xc820049f50 sp=0xc820049e60
runtime.main()
    /usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820049fa0 sp=0xc820049f50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820049fa8 sp=0xc820049fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
exit status 2
FAIL    github.com/sunwxg/golibwireshark    0.212s

```

**Comment by sunwxg** [comment]
Which version of go do yo use? I test on version 1.5.1 and 1.6.2.
